apiVersion: v1
kind: ServiceAccount
metadata:
  name: sriov-dp-sa
  namespace: kube-system
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: node-lister
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sriov-dp-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: node-lister
subjects:
- kind: ServiceAccount
  name: sriov-dp-sa
  namespace: kube-system
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: sriov-config
  namespace: kube-system
data:
  config.json: |
    {
      "resourceList":
      [
        {
          "resourceName": "sriov",
          "rootDevices": ["04:00.0"],
          "sriovMode": true,
          "deviceType": "netdevice"
        }
      ]
    }
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: sriov-device-plugin
  namespace: kube-system
spec:
  selector:
      matchLabels:
        name: sriov-device-plugin
  template:
    metadata:
      labels:
        name: sriov-device-plugin
    spec:
      serviceAccountName: sriov-dp-sa 
      initContainers:
      - name: init-sriov-dp
        image: amshinde/multus-sriov-shim-device-plugin:k8s-1.13
        command: [ "bash", "-c" ]
        args:
        - cp /tmp/cni/bin/{multus,sriov} /host/opt/cni/bin/;
          cp /tmp/etc/cni/net.d/* /host/etc/cni/net.d/;
          systemctl stop kubelet;
          cp /tmp/bin/kubelet /host/usr/bin/kubelet;
          echo "Restarting crio/containerd, kubelet";
          systemctl daemon-reload;
          systemctl restart containerd;
          systemctl restart crio;
          systemctl restart kubelet;
        volumeMounts:
        - name: usr-bin
          mountPath: /host/usr/bin
        - name: cni-bin
          mountPath: /host/opt/cni/bin
        - name: multus-cm
          mountPath: /tmp/etc/cni/net.d
        - name: cni-conf
          mountPath: /host/etc/cni/net.d
        - name: dbus
          mountPath: /var/run/dbus
        - name: systemd
          mountPath: /run/systemd
      containers:
      - name: sriov-dp
        image: amshinde/multus-sriov-shim-device-plugin:k8s-1.13
        command: [ "sh", "-c" ]
        args:
        - /tmp/bin/sriovdp --logtostderr -v 10;
          echo "exit status $?";
        volumeMounts:
        - name: net
          mountPath: /sys/class/net
          readOnly: true
        - name: dp-sock
          mountPath: /var/lib/kubelet/device-plugins/
          readOnly: false
        - mountPath: /etc/pcidp
          name: sriov-config
          readOnly: false
      volumes:
      - name: sriov-config
        configMap:
          name: sriov-config
      - name: usr-bin
        hostPath:
          path: /usr/bin
      - name: cni-bin
        hostPath:
          path: /opt/cni/bin
      - name: multus-cm
        configMap:
          name: multus-conf
      - name: cni-conf
        hostPath:
          path: /etc/cni/net.d
      - name: dbus
        hostPath:
          path: /var/run/dbus
      - name: systemd
        hostPath:
          path: /run/systemd
      - name: net
        hostPath:
          path: /sys/class/net
      - name: dp-sock
        hostPath:
          path: /var/lib/kubelet/device-plugins/
      hostNetwork: true
      hostPID: true

